### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by OpportunityLiu** [xmake-io/awesome-xmake#1]
搞了个 xmake 的 Github action

https://github.com/OpportunityLiu/github-action-setup-xmake

这有个例子
https://github.com/OpportunityLiu/UWPFlow/blob/master/.github/workflows/ccpp.yml
https://github.com/OpportunityLiu/UWPFlow/actions?workflow=C%2FC%2B%2B+CI

可以的话希望能移到本组织下

**Comment by waruqi** [comment]
可以，我邀请进xmake-io organization吧，你看看能否直接迁移进来。

**Comment by OpportunityLiu** [comment]
移过来了

**Comment by waruqi** [comment]
看到了。
